name: Test

on:
  push:
    branches:
      - main
      - add-github-action ##TO DO: remove this
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Invoke Tests
      shell: pwsh
      run: /Tests/Invoke-Tests
      