name: TestAndTag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Invoke Tests
      shell: pwsh
      run: Tests/Invoke-Tests.ps1
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: '**/TEST-*.xml'
  tag:
    name: Push Git Tag
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get latest tag
      uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      with:
        semver_only: true
    - name: Bump tag
      uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: minor
    - name: Push tag
      uses: actions-ecosystem/action-push-tag@v1
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      with:
        tag: ${{ steps.bump-semver.outputs.new_version }}
